small changes and bugfixes

diff --git a/tribler-bash b/tribler-bash
--- a/tribler-bash
+++ b/tribler-bash
@@ -152,14 +152,15 @@ curl_tribler() {
     curl_cmd+=( -H  "accept: application/json" )
     [[ "$2" == PUT ]] && curl_cmd+=( -H  "Content-Type: application/json" )
     [[ "$3" ]] && curl_cmd+=( -d "$3" )
-    curl_cmd+=( "http://localhost:{$apiport}/${1}" )
+    curl_cmd+=( "http://localhost:${apiport}/${1}" )
     
     debug -f "${curl_cmd[*]}"
     output="$( "${curl_cmd[@]}" )"
     ecode=$?
     
     if [[ "$ecode" != 0 ]]; then
-	err "CURL_ERROR_CODE:${ecode}"
+	err "CURL_ERROR_CODE=${ecode}"
+	err "Is Tribler running?"
 	return "$ecode"
     elif ! [[ "$output" ]]; then
 	err "Error: Empty output!"
@@ -190,7 +191,6 @@ populate_basics() {
     done
 
     [[ "$default_destination_path" ]] && return 0
-    debug -f curl
 
     tribler_settings_curl="$(curl_tribler settings GET )" || return
     default_destination_path="$( echo "$tribler_settings_curl" | jq_ .settings.download_defaults.saveas )"
@@ -204,58 +204,60 @@ populate_downloads_data() {
     debug ''; debug -f "start"
     populate_basics
 
-#    [[ "$DEBUG" ]] && { set -x; SET_X=1; }
-    if ! [[ "$last_checktime" && ( "$(( $SECONDS-$last_checktime ))" -le 2 ) ]]; then
-	debug -f "getting download data"
-        # skip this section if last check not long ago
-	
-        download_data="$(curl_tribler downloads GET)" || exit
-        last_checktime="$SECONDS"
-
-	debug -f "processing download data"
-	debug -f "populating array Hashes_all"
-        Hashes_all=( $(echo "$download_data" | jq -r -c ".downloads[].infohash") )
-	debug -f "Hashes_all: ${Hashes_all[*]}"
-
-        if ! [[ "${Hashes_all[*]}" ]]; then
-            debug -f "No torrents active"
-            return 0
-        fi
-
-	debug -f "Setting indexes"
-	declare -g -A Index
-	local i hash
-	i=1
-	for hash in "${Hashes_all[@]}"; do
-	    Index[$i]="$hash"
-	    debug -f "Index[$i]=$hash"
-	    i=$((i+1))
-	done
-
-	debug -f "Getting key names"
-        mapfile -t Keys_download < <(echo "$download_data" | jq -r -c ".downloads[0] | keys | .[]")
-        debug -f "Keys_download=${Keys_download[*]}"
-    else
+    if [[ "$last_checktime" && ( "$(( $SECONDS-$last_checktime ))" -le 2 ) ]]; then
 	debug -f "Last check not long time ago, skipping."
+	return 0
+    fi
+    
+    debug -f "getting download data"
+    # skip this section if last check not long ago
+	
+    download_data="$(curl_tribler downloads GET)" || exit
+    last_checktime="$SECONDS"
+
+    debug -f "processing download data"
+    debug -f "populating array Hashes_all"
+    Hashes_all=( $(echo "$download_data" | jq -r -c ".downloads[].infohash") )
+    debug -f "Hashes_all: ${Hashes_all[*]}"
+
+    if ! [[ "${Hashes_all[*]}" ]]; then
+        debug -f "No torrents active"
+        return 0
     fi
 
+    debug -f "Setting indexes"
+    declare -g -A Index
+    local i hash
+    i=1
+    for hash in "${Hashes_all[@]}"; do
+	Index[$i]="$hash"
+	debug -f "Index[$i]=$hash"
+	i=$((i+1))
+    done
+
+    debug -f "Getting key names"
+    mapfile -t Keys_download < <(echo "$download_data" | jq -r -c ".downloads[0] | keys | .[]")
+    debug -f "Keys_download=${Keys_download[*]}"
+    
     local hash associative_table_name key value
 
-    debug -f "Populating associative arrays"
+    debug -f -e "Populating associative arrays\n"
     for hash in "${Hashes_all[@]}"; do
-
+	
+	debug -f "[ HASH: ${hash} ]"
         [[ "$hash" && "$hash" =~ ^[a-zA-Z_0-9]+$ ]] ||\
             { err "empty or invalid chars in hash: '$hash'"; return 2; }
 	
         associative_table_name="hash_${hash}"
         declare -g -A "${associative_table_name}"
-	debug "declare -g -A \"${associative_table_name}\""
+	debug -f -e "\t declare -g -A \"${associative_table_name}\""
 
         for key in "${Keys_download[@]}"; do
 	    value="$(echo "$download_data" | jq -r -c ".downloads[] | select(.infohash | contains(\"${hash}\")) | .$key" )"
-	    debug -f "declare \"${associative_table_name}\"[\"$key\"]=\"$value\""
+	    debug -f -e "\t declare \"${associative_table_name}\"[\"$key\"]=\"$value\""
             declare -g "${associative_table_name}"["$key"]="$value"
         done
+	debug ''
     done
 #    [[ "$SET_X" ]] && { set +x; unset SET_X; }
     debug -f -e "end\n"
@@ -390,7 +392,7 @@ list() {
 	    line="${line}\t${seeds}\t${peers}"
 
 	    perc="$(echo "scale=2; $(get_download_data "$hash" progress)*100/1" | bc -l )" #%
-	    line="${line}\t${perc}"
+	    line="${line}\t${perc}%"
 	    
 	    status="$(get_download_data "$hash" status | sed 's/^DLSTATUS_//' | tr '[:upper:]' '[:lower:]' )"
 	    line="${line}\t${status}"
@@ -488,7 +490,7 @@ change_download_state() {
 	shift
     done
 
-    [[ "$state" ]] && payload=" \"state\": \"$2\" "
+    [[ "$state" ]] && payload=" \"state\": \"$state\" "
     if [[ "$hops" ]]; then
 	[[ "$payload" ]] && payload="${payload}, "
 	payload="\"anon_hops\": $hops"
